<div class="content-box-large">
			  				<div class="panel-heading">
					            <div class="panel-title">Add a New Category</div>					       
					        </div>
			  				<div class="panel-body">
			  					<form class="form-horizontal" role="form"  method="post" enctype="multipart/form-data">
								  <div class="form-group">
								    <label for="name" class="col-sm-2 control-label">Category Name</label>
								    <div class="col-sm-10">
								      <input type="text" class="form-control" id="name" name="category_name" placeholder="Category Name" required>
								    </div>
								  </div>
								  
								  <div class="form-group">
								    <label class="col-sm-2 control-label">Desciption</label>
								    <div class="col-sm-10">
								      <textarea class="form-control" name="category_description" required placeholder="Category Description" rows="3"></textarea>
								    </div>
								  </div>
								  
								  
								  <div class="form-group">
								    <label for="position" class="col-sm-2 control-label">Position</label>
								    <div class="col-sm-10">
								      <input type="int" class="form-control" id="position" name="position" placeholder="Position">
								    </div>
								  </div>
								 
								 <div class="form-group">
											<label class="col-md-2 control-label">Category Image</label>
											<div class="col-md-10">
												<input type="file" name="image" class="btn btn-default" id="image">
												<p class="help-block">
												
												</p>
											</div>
								</div>
								
								  <div class="form-group">
								  	<label class="col-md-2 control-label">Category Status</label>
								    <div class="col-sm-offset-2 col-sm-10">
								      <div class="checkbox">
								        <label>
								          <input type="hidden" name="status" value="0"/>
								          <input type="checkbox" name="status" value="1" checked> Enabled
								        </label>
								      </div>
								      
								    </div>
								  </div>
								  <div class="form-group">
								    <div class="col-sm-offset-2 col-sm-10">
								      <button type="submit" class="btn btn-primary">Submit</button>
								    </div>
								  </div>
								</form>
			  				</div>
</div>