<div class="content-box-large">
  				<div class="panel-heading">
					<div class="panel-title">Categories</div>
				</div>
  				<div class="panel-body">
  					<div class="table-responsive">
  						<table class="table">
			              <thead>
			                <tr>
			                  <th>#</th>
			                  <th>Name</th>
			                  <th>Description</th>
			                  <th>Position</th>
			                  <th>Actions</th>
			                </tr>
			              </thead>
			              <tbody>
			                <?php if($this->categories):?>
			                <?php foreach($this->categories as $category):?>
			                <tr>
			                  <td><?php echo $category->getCategoryId()?></td>
			                  <td><?php echo $category->getCategoryName()?></td>
			                  <td><?php echo $category->getCategoryDescription()?></td>
			                  <td><?php echo $category->getPosition()?></td>
			                  <td>
			                  <button class="btn btn-primary" onclick="window.location='<?php echo BASEURL?>/admin.php?controller=categories&action=edit&id=<?php echo $category->getId()?>'"><i class="glyphicon glyphicon-pencil"></i> Edit</button>
			                  <button class="btn btn-danger" onclick="return confirmDelete('<?php echo BASEURL?>/admin.php?controller=categories&action=delete&id=<?php echo $category->getId()?>','Are you sure to delete this category?')"><i class="glyphicon glyphicon-remove"></i> Delete</button>
			                  </td>
			                </tr>
			               <?php endforeach?>
			               <?php endif?>
			              </tbody>
			            </table>
  					</div>
  					
  					<div>
  					<div class="btn-group">
                     	<?php $page = 0; for($i=0;$i<=$this->totalCount;$i=$i+$this->numberPerPage):$page++;?>  
                     	<a href="<?php echo BASEURL?>/admin.php?controller=categories&action=index&page=<?php echo $page?>"><?php echo $page?></a>
                     	<?php endfor?>
                    </div>
  					</div>
  					
  					<button class="btn btn-info btn-lg" onclick="window.location='<?php echo BASEURL?>/admin.php?controller=categories&action=add'">Add New Category</button>
  				</div>
</div>