<div id="contents">
    			
	<style>
 .er li{
 	padding-top: 5px;
	padding-right: 0pt;
	padding-bottom: 5px;
	padding-left: 15px;
	background-color: transparent;
	background-repeat: no-repeat;
	background-attachment: scroll;
	background-position: 0pt 50%;
 }
</style>
<div class='er' style="padding: 30px 20px 130px;  margin: 0px 100px;">
<h1 style="background-image: url(&quot;/img/dot01.gif&quot;); background-repeat: repeat-x; background-attachment: scroll; background-position: 0pt 100%; font-size: 14px;">
The page you requested was not found.</h1>
<p >
	You may have clicked an expired link or mistyped the address. Some web addresses are case sensitive.
</p>
<p><?php echo $this->message?></p>
<br><br>
	<ul>
		<li><a style='text-decoration:underline' href="<?php echo BASEURL?>">Return home</a></li>
		
		<li><a style='text-decoration:underline' onclick="history.back();" href="javascript:;">Go back to the previous page</a></li>
	</ul>
<br><br>
</div>		
			</div>

