<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title><?php echo $this->pageTitle?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Bootstrap -->
    <link href="<?php echo BASEURL?>/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- styles -->
    <link href="<?php echo BASEURL?>/assets/css/styles.css" rel="stylesheet"> 
<link href="<?php echo BASEURL?>/assets/css/custom.css" rel="stylesheet"> 
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
    
     <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//code.jquery.com/jquery.js"></script>
    <!-- jQuery UI -->
    <script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<?php echo BASEURL?>/assets/bootstrap/js/bootstrap.min.js"></script>


    <script src="<?php echo BASEURL?>/assets/js/custom.js"></script>
    
    
	
	<script>
		function confirmDelete($url,$message){
			if(confirm($message)){
				window.location = $url;
			}

			return false;
		}
		
	</script>
</head>

<body style="">
	<?php echo $this->render('admin-header.phtml');	?>
    
     <div class="page-content">
    	<div class="row">
    		<?php echo $this->render('admin-left.phtml');	?>
    		
    		<div class="col-md-10">
				<?php if($this->session->getData('flashMessage')):?>
						    <div class="messages">
						    
						    <?php foreach ($this->session->getData('flashMessage') as $type=>$messages):?>
						    <div class="alert alert-<?php echo $type?>">
						    <?php foreach ($messages as $key=>$message):?>
						    <div class="message-item">
						    <?php echo $message;   ?>
						    </div>
						    <?php endforeach;?>
						    
						    </div>
						     <?php endforeach;
						     $this->session->unsetData('flashMessage')
						     ?>
						    </div>
						    <?php endif?>
				    
			    	<?php  	echo $this->layout->content; ?>
			    
			 </div>
	 
	 
    	</div>
    </div>
   
    
    
    <?php echo $this->render('admin-footer.phtml');	?>
</body>
</html>    
    