<div class="col-md-2">
		  	<div class="sidebar content-box" style="display: block;">
                <ul class="nav">
                    <!-- Main menu -->
                    <li class="current"><a href="<?php echo BASEURL?>/admin"><i class="glyphicon glyphicon-home"></i> Dashboard</a></li>
                    <li><a href="<?php echo BASEURL?>/admin.php?controller=categories"><i class="glyphicon glyphicon-calendar"></i> Manage Categories</a></li>
                    <li><a href="<?php echo BASEURL?>/admin.php?controller=products"><i class="glyphicon glyphicon-calendar"></i> Manage Products</a></li>
                  
                   
                </ul>
             </div>
</div>