<div class="header">
	     <div class="container">
	        <div class="row">
	           <div class="col-md-5">
	              <!-- Logo -->
	              <div class="logo">
	                 <h1><a href="<?php echo BASEURL?>/admin.php">Bookstore Admin Panel</a></h1>
	              </div>
	           </div>
	           <div class="col-md-3">
	             
	           </div>
	          
	           <div class="col-md-4">
	           	   <?php if($this->admin):?>
	              <div class="navbar navbar-inverse" role="banner">
	                  <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation"
	                  style="padding-top: 15px;padding-bottom: 15px; color:#fff"
	                  >
	                    Welcome, <?php echo $this->admin->getUsername()?> | <a style="color:#fff" href="<?php echo BASEURL?>/admin.php?contoller=index&action=logout">Log out</a>
	                  </nav>
	              </div>
	              <?php endif?>
	           </div>
	        </div>
	     </div>
</div>
